version: '3.8'

services:
  # Service Angular en mode développement
  settly-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: settly-frontend
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    # Redémarrage automatique en cas d'erreur
    restart: unless-stopped

# Volumes pour les node_modules
volumes:
  node_modules:

# Réseau défini
networks:
  settly-network:
    driver: bridge 