version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
    ports:
      - "4200"
    environment:
      - NODE_ENV=production
      - PORT=4200
    restart: unless-stopped